/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TrustedBridge_constants.h"

namespace TrustedBridge {

const TrustedBridgeConstants g_TrustedBridge_constants;

TrustedBridgeConstants::TrustedBridgeConstants() {
}

} // namespace

