/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TrustedBridge_CONSTANTS_H
#define TrustedBridge_CONSTANTS_H

#include "TrustedBridge_types.h"

namespace TrustedBridge {

class TrustedBridgeConstants {
 public:
  TrustedBridgeConstants();

};

extern const TrustedBridgeConstants g_TrustedBridge_constants;

} // namespace

#endif
